name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace "main" with the branch you want to trigger the workflow for

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and push steps here

      - name: Build Docker image
        run: docker build -t manidocker1248/react-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push manidocker1248/react-app:latest

